### ISSUE TITLE
SVG font-family is being replaced

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/xml2rfc#923]
### Describe the issue

SVG images in documents that have a `font-family="monospace"` attribute are having that attribute incorrectly replaced with `font-family="Roboto Mono"`.

Please, do not apply style rules to content in this way.  The best way to apply font changes to content like this is with a stylesheet.

In case this is not obvious how to fix, this is the rule that I have:

```css
svg[font-family~="monospace" i], svg [font-family~="monospace" i] {
  font-family: var(--font-mono);
}
```

Note that because "Roboto Mono" is loaded by the default stylesheet, if that stylesheet is not loaded (I use `--css` to load an alternative), diagrams can be broken by this change.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)
